# Session 5: From Single to Multiple Values: Arrays and NumPy

## Overview
This tutorial builds on your knowledge of variables, assignments, and functions by introducing arrays and the NumPy library in Python. By the end of this session, you will understand how to create and manipulate arrays, perform operations on multiple arrays, and use NumPy functions for efficient calculations.

## Prerequisites
- Basic understanding of Python variables, data types, and functions


## Part 1: Introduction to Arrays (15 minutes)

### What is an Array?
- An array is a data structure that can hold multiple values of the same type.
- Arrays are useful for storing lists of data and performing operations on multiple elements at once.


### Creating an Array
In Python, arrays can be created using lists.

#### Example:


In [2]:
my_array = [1, 2, 3, 4, 5]
print(my_array)


[1, 2, 3, 4, 5]


### Accessing Elements
Elements in an array can be accessed using their index.

#### Example:


In [3]:
print(my_array[0])  # Output: 1
print(my_array[2])  # Output: 3


1
3


### Modifying Elements
You can modify elements in an array by assigning new values to specific indices.

#### Example:


In [4]:
my_array[1] = 10
print(my_array)  # Output: [1, 10, 3, 4, 5]


[1, 10, 3, 4, 5]


### Practice Problem 1
- Create an array of numbers with the values `[10, 20, 30, 40, 50]`.
- Change the second element to 25.
- Print the modified array.

#### Solution:


In [5]:
numbers = [10, 20, 30, 40, 50]
numbers[1] = 25
print(numbers)  # Output: [10, 25, 30, 40, 50]


[10, 25, 30, 40, 50]


## Part 2: Introduction to NumPy (20 minutes)

### What is NumPy?
- NumPy is a powerful library for numerical computing in Python.
- It provides support for arrays and matrices, along with a collection of mathematical functions to operate on them.


### Installing NumPy (should already be installed)
NumPy can be installed using pip: pip install numpy


### Creating NumPy Arrays

#### Example:


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


### Basic Operations

#### Example:


In [7]:
arr = np.array([1, 2, 3, 4, 5])
print(arr + 10)  # Output: [11 12 13 14 15]
print(arr * 2)   # Output: [ 2  4  6  8 10]


[11 12 13 14 15]
[ 2  4  6  8 10]


### Practice Problem 2
- Create a NumPy array `my_array` with values `[5, 10, 15, 20, 25]`.
- Multiply each element by 3 and print the result.

#### Solution:


In [8]:
my_array = np.array([5, 10, 15, 20, 25])
print(my_array * 3)  # Output: [15 30 45 60 75]


[15 30 45 60 75]


## Part 3: Manipulating Arrays (20 minutes)

### Element-wise Operations
NumPy allows element-wise operations on arrays.

#### Example:


In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # Output: [5 7 9]
print(arr1 * arr2)  # Output: [ 4 10 18]


[5 7 9]
[ 4 10 18]


### Universal Functions
NumPy provides universal functions for element-wise operations.

#### Example:


In [10]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sqrt(arr))  # Output: [1.         1.41421356 1.73205081 2.         2.23606798]


[1.         1.41421356 1.73205081 2.         2.23606798]


### Practice Problem 3
- Create two NumPy arrays `a` and `b` with values `[1, 2, 3]` and `[4, 5, 6]` respectively.
- Add the two arrays and print the result.
- Calculate the square root of the resulting array and print it.

#### Solution:


In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b
print(result)          # Output: [5 7 9]
print(np.sqrt(result)) # Output: [2.23606798 2.64575131 3.        ]


[5 7 9]
[2.23606798 2.64575131 3.        ]


## Part 4: Working with Multiple Arrays (20 minutes)

### Stacking Arrays
Arrays can be stacked together using `np.vstack` (vertical stack) and `np.hstack` (horizontal stack).

#### Example:


In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.vstack((arr1, arr2)))
# Output:
# [[1 2 3]
#  [4 5 6]]

print(np.hstack((arr1, arr2)))
# Output: [1 2 3 4 5 6]


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


### Reshaping Arrays
Arrays can be reshaped using the `reshape` method.

#### Example:


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)
# Output:
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


### Practice Problem 4
- Create a NumPy array `c` with values `[7, 8, 9]`.
- Stack `a` and `c` vertically and print the result.
- Reshape the result into a 3x2 array and print it.

#### Solution:


In [14]:
a = np.array([1, 2, 3])
c = np.array([7, 8, 9])
stacked = np.vstack((a, c))
print(stacked)
# Output:
# [[1 2 3]
#  [7 8 9]]

reshaped = stacked.reshape(3, 2)
print(reshaped)
# Output:
# [[1 2]
#  [3 7]
#  [8 9]]


[[1 2 3]
 [7 8 9]]
[[1 2]
 [3 7]
 [8 9]]


## Part 5: NumPy Functions for Multiple Values (20 minutes)

### Using NumPy for Mathematical Operations

#### Example:


In [15]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # Output: 3.0
print(np.sum(arr))   # Output: 15
print(np.max(arr))   # Output: 5
print(np.min(arr))   # Output: 1


3.0
15
5
1


### Solving Equations with NumPy
NumPy can solve equations efficiently.

#### Example:
# Solving a system of linear equations:
# 2x + y = 5
# x + 3y = 10


In [16]:
A = np.array([[2, 1], [1, 3]])
B = np.array([5, 10])

solution = np.linalg.solve(A, B)
print(solution)  # Output: [1. 3.]


[1. 3.]


### Practice Problem 5
- Create a NumPy array `d` with values `[10, 20, 30, 40, 50]`.
- Calculate the mean, sum, max, and min of the array `d` and print the results.
- Solve the following system of equations using NumPy:
  - 3x + 2y = 18
  - 2x + 3y = 18

#### Solution:


In [17]:
d = np.array([10, 20, 30, 40, 50])
print(np.mean(d))  # Output: 30.0
print(np.sum(d))   # Output: 150
print(np.max(d))   # Output: 50
print(np.min(d))   # Output: 10

# Solving the system of equations:
# 3x + 2y = 18
# 2x + 3y = 18
A = np.array([[3, 2], [2, 3]])
B = np.array([18, 18])

solution = np.linalg.solve(A, B)
print(solution)  # Output: [4. 2.]


30.0
150
50
10
[3.6 3.6]


## Conclusion and Q&A (10 minutes)
- Review the key concepts covered: arrays, NumPy, element-wise operations, stacking and reshaping arrays, and using NumPy functions for calculations.
- Encourage practice and experimentation.
- Open the floor for any questions and further clarifications.
